# modified from real_pusht_image.yaml to support Leap Hand dataset

name: real_image

image_shape: [3, 240, 320]
dataset_path: data/leap_real/real_leap_20240605

shape_meta: &shape_meta # acceptable types: rgb, low_dim
  obs:
    camera_0:
      shape: ${task.image_shape}
      type: rgb
    camera_1:
      shape: ${task.image_shape}
      type: rgb
    robot_joint:
      shape: [16]
      type: low_dim
    object_pose:
      shape: [7]
      type: low_dim
  action:
    shape: [16]

env_runner:
  _target_: diffusion_policy.env_runner.real_leap_image_runner.RealLeapImageRunner

dataset:
  _target_: diffusion_policy.dataset.real_leap_image_dataset.RealLeapImageDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  use_cache: True
  seed: 42
  val_ratio: 0.00
  max_train_episodes: null
  delta_action: False
